spring:
  main:
    allow-circular-references: true

  datasource:
    url: ENC(ZRl6t1LSC6ZB5kJNthOJsZEy2eIDkbXlioy2VCNO4P5E17WBIkarVUYsq1xgQ5K8Ki3J2hTpBF2gMOOXW65NmddR+9kXgudSa2QbN8iFfq9wW3O1XvYKSBe901Clrz5f83YdHcWGTrdzLSoWPRUJ5A==)
    driver-class-name: org.mariadb.jdbc.Driver # runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    username: ENC(/+lB26gh6Xwda/uc8XN6Dg==)
    password: ENC(AKia6xht1TJEbrcNNO5pOg==)

    hikari:
      connection-init-sql: SELECT 1
      minimum-idle: 1
      idle-timeout: 300000
      maximum-pool-size: 31
      max-lifetime: 540000
      username: ENC(/+lB26gh6Xwda/uc8XN6Dg==)
      password: ENC(AKia6xht1TJEbrcNNO5pOg==)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
          hibernate:
            format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 660175457618-mkbjeknutbeq8vcr7j1b5kr16f0idu2e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 807673720975917
            client-secret: 458f534c42198473702a429fda7fbf38
            scope:
              - email
              - public_profile

          naver:
            client-id: XfdVJMkCSWBk5H8QI0j_
            client-secret: WDzLpoa54_
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # Callback URL (google/facebook은 설정되어있으나 네이버는 X)

          kakao:
            client-id: 1b315168d3950e6689e59cc899600c0f
            client-secret: eRCWUQjXZlzoBqkS8QQunGaNqNh37LJo
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

        #naver라는 registration은 없기 때문에 만들어 주어야함 (Provider ID must be specified for client registration 'naver')
        provider:
           naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받음  response라는 키값으로 네이버가 리턴해줌

           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id


jasypt:
  encryptor:
    bean: jasyptStringEncryptor

